name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Checkout and build
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run build.sh
        run: |
          printenv
          ./sources/fetch_sources.sh
          ./build.sh
